## => Site Settings
##############################
text_skin: dark
highlight_theme: tomorrow-night
url     : https://ibogovic-hub.github.io
baseurl :
show_date: true
title   : Ivan Bogović
description: >
  IT Engineering Leader | Infrastructure, Security & Scalable Operations | Zürich, Switzerland


## => Language and Timezone
##############################
lang: en
timezone: Europe/Zurich


## => Author and Social
##############################
author:
  type      : person
  name      : Ivan Bogović
  url       : https://ibogovic-hub.github.io
  avatar    : assets/images/avatar.jpg
  bio       : Manager, IT Engineering at Open Systems AG. Infrastructure, Security & Scalable Operations across 180+ countries.
  email     : bogovic@pm.me
  linkedin  : bogovic
  github    : ibogovic-hub
  telegram  : ibogovic


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: ibogovic-hub/ibogovic-hub.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    :
  home    :
  archive : /archive.html
  rss     :


## => Post
##############################
excerpt_separator: <!--more-->
license: CC-BY-NC-4.0
toc:
  selectors:


## => Markdown Enhancements
##############################
mathjax: false
mathjax_autoNumber: false
mermaid: true
chart: false


## => Paginate
##############################
paginate: 8
paginate_path: /page:num


## => Sources
##############################
sources:


## => Sharing
##############################
sharing:
  provider: false


## => Comments
##############################
comments:
  provider: false


## => Pageview
##############################
pageview:
  provider: false


## => Search
##############################
search:
  provider: default


## => Analytics
##############################
analytics:
  provider: false


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - push.sh
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: article
      sharing: false
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: false
      pageview: false


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
